### ISSUE TITLE
Error: Calling Formula.sha1 is disabled! Use Formula.sha256 instead

### ISSUE THREAD

**Issue by calvingit** [JiriTrecak/homebrew-laurine#3]
When i run `brew upgrade`, then the below error occurs
```bash
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/jiritrecak/homebrew-laurine/laurine.rb:4:in `<class:Laurine>'
Please report this to the jiritrecak/laurine tap!
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:86:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:94:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/usr/local/Homebrew/Library/Taps/jiritrecak/homebrew-laurine/laurine.rb:4:in `<class:Laurine>'
/usr/local/Homebrew/Library/Taps/jiritrecak/homebrew-laurine/laurine.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:200:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:240:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:271:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:254:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1364:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1362:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1362:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:859:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by JiriTrecak** [comment]
Hello Calvin,

I have not updated the brew configuration for a while now - thank you for reminding me. Will do over the weekend, for both 2.2 and 3.0 versions. 

Have a great day
Jiri

**Comment by calvingit** [comment]
OK，thank you very much
